### ISSUE TITLE
io.netty.channel.ChannelPipelineException (warning-level log)

### ISSUE THREAD

**Issue by paoloboni** [paoloboni/binance-scala-client#111]
... has been reported while running the following code:

```
        BinanceClient
          .createFutureClient[IO](_)
          .use { client =>
            Stream
              .eval(Clock[IO].realTime)
              .map(_.toMillis)
              .map(currentTime =>
                KLines(
                  "BTCUSDT",
                  Interval.`1m`,
                  Instant.ofEpochMilli(currentTime - 60000),
                  Instant.ofEpochMilli(currentTime + 1000),
                  1
                )
              )
              .flatMap(x => client.getKLines(x).last)
              .collect { case Some(c) => c }
              .repeat
              .metered(500.millis)
              .zipWithIndex
              .evalTap(x => IO.println(s"${x._2}\n"))
              .compile
              .drain
```

and while running the build:
```
[AsyncHttpClient-7-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.ChannelPipelineException: org.asynchttpclient.netty.handler.StreamedResponsePublisher.handlerRemoved() has thrown an exception.
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:640)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:477)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:417)
	at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:94)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: dispatcher already shutdown
	at cats.effect.std.Dispatcher$$anon$1.unsafeToFutureCancelable(Dispatcher.scala:271)
	at cats.effect.std.Dispatcher.unsafeToFuture(Dispatcher.scala:62)
	at cats.effect.std.Dispatcher.unsafeToFuture$(Dispatcher.scala:61)
	at cats.effect.std.Dispatcher$$anon$1.unsafeToFuture(Dispatcher.scala:178)
	at cats.effect.std.Dispatcher$$anon$1.$anonfun$unsafeToFutureCancelable$3(Dispatcher.scala:190)
	at cats.effect.std.Dispatcher$$anon$1.loop$2(Dispatcher.scala:255)
	at cats.effect.std.Dispatcher$$anon$1.$anonfun$unsafeToFutureCancelable$6(Dispatcher.scala:259)
	at cats.effect.std.Dispatcher$$anon$1.unsafeToFutureCancelable(Dispatcher.scala:267)
	at cats.effect.std.DispatcherPlatform.unsafeRunTimed(DispatcherPlatform.scala:38)
	at cats.effect.std.DispatcherPlatform.unsafeRunTimed$(DispatcherPlatform.scala:37)
	at cats.effect.std.Dispatcher$$anon$1.unsafeRunTimed(Dispatcher.scala:178)
	at cats.effect.std.DispatcherPlatform.unsafeRunSync(DispatcherPlatform.scala:30)
	at cats.effect.std.DispatcherPlatform.unsafeRunSync$(DispatcherPlatform.scala:29)
	at cats.effect.std.Dispatcher$$anon$1.unsafeRunSync(Dispatcher.scala:178)
	at fs2.interop.reactivestreams.StreamSubscriber.onComplete(StreamSubscriber.scala:60)
	at sttp.client3.asynchttpclient.AsyncHttpClientBackend$$anon$1$$anon$2$$anon$3.onComplete(AsyncHttpClientBackend.scala:108)
	at org.asynchttpclient.netty.handler.StreamedResponsePublisher$ErrorReplacingSubscriber.onComplete(StreamedResponsePublisher.java:115)
	at com.typesafe.netty.HandlerPublisher.complete(HandlerPublisher.java:408)
	at com.typesafe.netty.HandlerPublisher.handlerRemoved(HandlerPublisher.java:395)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:946)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)
	... 30 more
```

**Comment by paoloboni** [comment]
This is no longer an issue. Closing
